<?php
//
// Copyright (c) 2017 Grigore Stefan, <g_stefan@yahoo.com>
// Created by Grigore Stefan <g_stefan@yahoo.com>
//
// The MIT License (MIT) <http://opensource.org/licenses/MIT>
//

defined('XYO_CLOUD') or die('Access is denied');

//
$this->setModule(null,null,"lib");
//
$this->setModule("lib",null,"lib-material-icons");
$this->setModule("lib",null,"lib-roboto-regular");
$this->setModule("lib",null,"lib-font-awesome");
$this->setModule("lib",null,"lib-ionicons");
$this->setModule("lib",null,"lib-jquery");
$this->setModule("lib",null,"lib-normalize");
$this->setModule("lib",null,"lib-select2");
$this->setModule("lib",null,"lib-air-datepicker");
//
$this->setModule(null,null,"xui");
$this->setModule("xui",null,"xui-core");
$this->setModule("xui",null,"xui-effect-ripple");
$this->setModule("xui",null,"xui-responsive");
$this->setModule("xui",null,"xui-elevation");
$this->setModule("xui",null,"xui-typography");
$this->setModule("xui",null,"xui-color");
$this->setModule("xui",null,"xui-palette");
$this->setModule("xui",null,"xui-form");
$this->setModule("xui",null,"xui-toggle");
$this->setModule("xui",null,"xui-dashboard");
$this->setModule("xui",null,"xui-box");
$this->setModule("xui",null,"xui-panel");
$this->setModule("xui",null,"xui-toolbar");
$this->setModule("xui",null,"xui-application");
//
//
$this->setModule("lib",null,"lib-bootstrap");
$this->setModule("lib",null,"lib-bootstrap-back-to-top");
$this->setModule("lib",null,"lib-bootstrap-datepicker");
$this->setModule("lib",null,"lib-bootstrap-datetimepicker");
$this->setModule("lib",null,"lib-bootstrap-dialog");
$this->setModule("lib",null,"lib-bootstrap-feedback-left");
$this->setModule("lib",null,"lib-bootstrap-fileinput");
$this->setModule("lib",null,"lib-bootstrap-select");
$this->setModule("lib",null,"lib-bootstrap-smartmenus");
$this->setModule("lib",null,"lib-d3");
$this->setModule("lib",null,"lib-js-cookie");
$this->setModule("lib",null,"lib-jquery-form");
$this->setModule("lib",null,"lib-jquery-stickytableheaders");
$this->setModule("lib",null,"lib-jquery-typeahead");
$this->setModule("lib",null,"lib-material-components-web");
$this->setModule("lib",null,"lib-material-icons");
$this->setModule("lib",null,"lib-md5");
$this->setModule("lib",null,"lib-moment");
$this->setModule("lib",null,"lib-nvd3");
$this->setModule("lib",null,"lib-pear-archive-tar");
$this->setModule("lib",null,"lib-roboto-regular");
$this->setModule("lib",null,"lib-slimbox2");
$this->setModule("lib",null,"lib-tinymce");
//
$this->setModule(null,null,"xyo");
//
$this->setModule("xyo",null,"xyo-mod-application");
$this->setModule("xyo",null,"xyo-mod-ds-acl");
$this->setModule("xyo",null,"xyo-mod-ds-loader-mod");
$this->setModule("xyo",null,"xyo-mod-ds-user");
$this->setModule("xyo",null,"xyo-mod-jsonx");
$this->setModule("xyo",null,"xyo-mod-setup");
$this->setModule("xyo",null,"xyo-mod-thumbnail");
//
$this->setModule(null,null,"xyo-app");
$this->setModule("xyo-app",null,"xyo-mod-xui-sidebar");
$this->setModule("xyo-app",null,"xyo-app-dashboard");
$this->setModule("xyo-app",null,"xyo-mod-panel2");
//
